# Generated by Django 5.1.4 on 2025-01-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioexamples',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
